const bcrypt = require('bcryptjs');
const productData = {
    users:[
        {
            User_name: 'John',
            email: 'john@example.com',
            password: bcrypt.hashSync('123'),
            isAdmin : false,
        },
        {
            User_name: 'Ganpati',
            email: 'Ganpati@example.com',
            password: bcrypt.hashSync('123'),
            isAdmin : true,
        },
        {
            User_name: 'Swpnil',
            email: 'Swpnil@example.com',
            password: bcrypt.hashSync('123'),
            isAdmin : false,
        },
        {
            User_name: 'Pavani',
            email: 'pavani@gmail.com',
            password: bcrypt.hashSync('123'),
            isAdmin : true,
        }
    ],
    products :[
        {
            Product_name: "Pink Banarasi Saree",
            slug: "banarasiSaree1",
            Category: "Sarees",
            Product_image: '/Assets/banarasiSaree-1.jpg',
            Product_Price: 5049,
            count_InStock: 50,
            Brand: 'Yashika',
            Product_Rating: 4.0,
            numReviews: 5,
            Description : 'pink and gold combination Banasaree Saree',
        },
        {
            Product_name: "Peach Banarasi Saree",
            slug: "banarasisaree2",
            Category: "Sarees",
            Product_image: '/Assets/banarasiSaree-2.jpg',
            Product_Price: 3049,
            count_InStock: 30,
            Brand: 'Yashika',
            Product_Rating: 4.3,
            numReviews: 5,
            Description : 'light peach colour complete worked Banasaree Saree',
        },
        {
            Product_name: "Banarasi Saree",
            slug: "banarasisaree3",
            Category: "Sarees",
            Product_image: '/Assets/banarasiSaree-3.jpg',
            Product_Price:6049,
            count_InStock: 20,
            Brand: 'Yashika',
            Product_Rating: 5,
            numReviews: 5,
            Description : 'peach colour complete worked Banasaree Saree',
        },
        {
            Product_name: "Blue Plazo Set",
            slug: "plazo1",
            Category: "Salwar",
            Product_image: '/Assets/blueSalwarSuit-4.jpg',
            Product_Price:649.00,
            count_InStock: 30,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Blue colour printed plazo set with dupatta',
        },
        {
            Product_name: "Green Salwar Suit",
            slug: "salwarsuit1",
            Category: "Salwar",
            Product_image: '/Assets/greenSalwarSuit-3.jpg',
            Product_Price:749.00,
            count_InStock: 40,
            Brand: 'Yashika',
            Product_Rating: 1.9,
            numReviews: 5,
            Description : 'Green colour printed long seelves salwar suit set',
        },
        {
            Product_name: "Pink Salwar suit set",
            slug: "salwarsuit2",
            Category: "Salwar",
            Product_image: '/Assets/pinkSalwarSuit-1.jpg',
            Product_Price:549.00,
            count_InStock: 0,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Pink colour printed long seelves salwar suit set',
        },
        {
            Product_name: "Purple Chudidar Set",
            slug: "salwarsuit3",
            Category: "Salwar",
            Product_image: '/Assets/purpleSalwarSuit-2.jpg',
            Product_Price:849.00,
            count_InStock: 0,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Purple colour printed long seelves chudidar set',
        },
        {
            Product_name: "Navy Blue long Gown",
            slug: "gown1",
            Category: "Gown",
            Product_image: '/Assets/dress1.jpg',
            Product_Price:799.00,
            count_InStock: 4,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Navy Blue long printed gown',
        },
        {
            Product_name: "Black long Gown",
            slug: "gown2",
            Category: "Gown",
            Product_image: '/Assets/dress2.jpg',
            Product_Price:999.00,
            count_InStock: 10,
            Brand: 'Yashika',
            Product_Rating: 2.9,
            numReviews: 5,
            Description : 'Black colour long Annarkali pattern grown with duptta',
        },
        {
            Product_name: "Long Gown",
            slug: "gown3",
            Category: "Gown",
            Product_image: '/Assets/dress5.jpg',
            Product_Price:849.00,
            count_InStock: 0,
            Brand: 'Yashika',
            Product_Rating: 3.9,
            numReviews: 5,
            Description : 'Peacock Green long printed gown',
        },
        {
            Product_name: "Full Seelves Gown",
            slug: "gown4",
            Category: "Gown",
            Product_image: '/Assets/dress6.jpg',
            Product_Price:1100.00,
            count_InStock: 9,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Maron colour long printed gown with full seelves',
        },
        {
            Product_name: "Blue Long Gown",
            slug: "gown5",
            Category: "Gown",
            Product_image: '/Assets/dress7.jpg',
            Product_Price:649.00,
            count_InStock: 3,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Blue colour printed long gown',
        },
        {
            Product_name: "Kurti",
            slug: "kurti",
            Category: "Salwar",
            Product_image: '/Assets/salwarkamijpeacockgreen.jpg',
            Product_Price:799.00,
            count_InStock: 0,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Peacock Green kurta paijama set',
        },
        {
            Product_name: "Peach Saree",
            slug: "saree1",
            Category: "Sarees",
            Product_image: '/Assets/sareedes-1.jpg',
            Product_Price:2959.00,
            count_InStock: 10,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Peach colour plain saree with border',
        },
        {
            Product_name: "Blue Saree",
            slug: "saree2",
            Category: "Sarees",
            Product_image: '/Assets/sareedes-2.jpg',
            Product_Price:3589.00,
            count_InStock: 0,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Sky Blue colour plain saree with border',
        },
        {
            Product_name: "Peacock Green Saree",
            slug: "saree3",
            Category: "Sarees",
            Product_image: '/Assets/sareedes-3.jpeg',
            Product_Price:2592.00,
            count_InStock: 0,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Dark Peacock Green colour plain saree with border',
        },
        {
            Product_name: "Pure Silk Saree",
            slug: "silklsaree1",
            Category: "Sarees",
            Product_image: '/Assets/silklSaree-1.jpg',
            Product_Price:2500.00,
            count_InStock: 50,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Dark Peach Colour silk saree with heavy border',
        },
        {
            Product_name: "Silk Saree",
            slug: "silklsaree2",
            Category: "Sarees",
            Product_image: '/Assets/silklSaree-2.jpg',
            Product_Price:3500.00,
            count_InStock: 30,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Light Peach Colour silk saree with light border',
        },
        {
            Product_name: "Silk Worked Saree",
            slug: "silksaree3",
            Category: "Sarees",
            Product_image: '/Assets/silklSaree-3.jpg',
            Product_Price:2459.00,
            count_InStock: 60,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Heavy Worked Party wear saree',
        },
        {
            Product_name: "Gray Silk Saree",
            slug: "silksaree4",
            Category: "Sarees",
            Product_image: '/Assets/silklSaree-4.jpg',
            Product_Price:2649.00,
            count_InStock: 10,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Gray and Black Party wear saree',
        },
        {
            Product_name: "Peach Silk Saree",
            slug: "silksaree5",
            Category: "Sarees",
            Product_image: '/Assets/silklSaree-5.jpg',
            Product_Price:3649.00,
            count_InStock: 30,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Gray and Dark Peach Party wear saree',
        },
        {
            Product_name: "Light Wedding Gown",
            slug: "weddingGown1",
            Category: "Wedding Gown",
            Product_image: '/Assets/WeddingGown-1.jpg',
            Product_Price:10649.00,
            count_InStock: 20,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'White Wedding Gown',
        },
        {
            Product_name: "plain Wedding Gown",
            slug: "weddingGown2",
            Category: "Wedding Gown",
            Product_image: '/Assets/WeddingGown-2.jpg',
            Product_Price:9649.00,
            count_InStock: 9,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Plain White Wedding Gown',
        },
        {
            Product_name: "Worked Wedding Gown",
            slug: "weddinggown3",
            Category: "Wedding Gown",
            Product_image: '/Assets/WeddingGown-3.jpg',
            Product_Price:11649.00,
            count_InStock: 4,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Light worked White Wedding Gown',
        },
        {
            Product_name: "Wedding Gown",
            slug: "weddinggown4",
            Category: "Wedding Gown",
            Product_image: '/Assets/WeddingGown-4.jpg',
            Product_Price:12649.00,
            count_InStock: 3,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'White Wedding Gown',
        },
        {
            Product_name: "Extra long Wedding Gown",
            slug: "weddinggown5",
            Category: "Wedding Gown",
            Product_image: '/Assets/WeddingGown-5.jpg',
            Product_Price:15649.00,
            count_InStock: 2,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Extra large length White Wedding Gown',
        },
        {
            Product_name: "Yashika Yellow Saree ",
            slug: "YaSaree1101",
            Category: "Sarees",
            Product_image: '/Assets/yellowSaree-1.jpg',
            Product_Price:1649.00,
            count_InStock: 0,
            Brand: 'Yashika',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Yellow Saree Collections',
        },
        {
            Product_name: "Avi Saree collection",
            slug: "YaSaree1102",
            Category: "Sarees",
            Product_image: '/Assets/yellowSaree-2.jpg',
            Product_Price:949.00,
            count_InStock: 30,
            Brand: 'Avi',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Yellow Saree Collections',
        },
        {
            Product_name: "Vaishanavi Yellow Saree",
            slug: "YaSaree1103",
            Category: "Sarees",
            Product_image: '/Assets/yellowSaree-3.jpg',
            Product_Price:849.00,
            count_InStock: 20,
            Brand: 'Vaishanavi',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Yellow Saree Collections',
        },
        {
            Product_name: "Yellow Saree",
            slug: "YaSaree1104",
            Category: "Sarees",
            Product_image: '/Assets/yellowSaree-4.jpg',
            Product_Price:949.00,
            count_InStock: 5,
            Brand: 'Vaishanavi',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Yellow Saree Collections',
        },
        {
            Product_name: "Yakshini Yellow Saree",
            slug: "YaSaree1105",
            Category: "Sarees",
            Product_image: '/Assets/yellowSaree-5.jpg',
            Product_Price:649.00,
            count_InStock: 10,
            Brand: 'Yakshini',
            Product_Rating: 4.9,
            numReviews: 5,
            Description : 'Yellow Saree Collections',
        },
    ]
}

module.exports = productData;